name: Bug Report
description: Please provide detailed information to help us quickly identify the issue.
title: "[BUG] Brief description of the issue"
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us improve the plugin! Please describe the issue in as much detail as possible. This will greatly help us resolve it quickly.

  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: Provide the version number of the Chrome plugin you're using.
      placeholder: "e.g., 1.3.5"
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Chrome Browser Version
      description: You can find this information at chrome://version.
      placeholder: "e.g., 119.0.6045.199"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Briefly describe the issue you're experiencing.
      placeholder: |
        e.g.,
        The plugin crashes and becomes unresponsive after clicking the button.
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to Reproduce
      description: Please list detailed steps to reproduce the issue.
      placeholder: |
        e.g.,
        1. Open the plugin.
        2. Click the "Start Sync" button.
        3. Wait 5 seconds, and the page crashes.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe the expected behavior of the plugin.
      placeholder: |
        e.g.,
        The plugin synchronizes data normally without crashing.
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Attachments
      description: Add any relevant screenshots, videos, or logs here.
      placeholder: |
        Drag and drop images here, or paste links.
    validations:
      required: false
